#!/usr/bin/env bash
# Installing nginx on our webserver

Update the apt repository 
2. Install nginx 
3. ufw allow 'Nginx HTTP'
4. echo 'Hello World' > /var/www/html/index.html
5. service nginx restart
